### ISSUE TITLE
jenkins role in Ansible fails various tasks due to "HTTP Error 403: No valid crumb was included in the request"

### ISSUE THREAD

**Issue by ghost** [vfarcic/ms-lifecycle#3]
# Replication

Replicable with a fresh run of:
`vagrant up cd prod swarm-master swarm-node-1 swarm-node-2`
Then (using the jenkins:latest image from Docker Hub), running

```
ansible-playbook /vagrant/ansible/jenkins-node-swarm.yml \
-i /vagrant/ansible/hosts/prod

ansible-playbook /vagrant/ansible/jenkins.yml -c local
```
# Error

At this point in `ms-lifecycle/ansible/roles/jenkins/tasks/main.yml`:

```
- name: Plugins are installed
  shell: "curl -X POST \
    -d '<jenkins><install plugin=\"{{ item }}@latest\" /></jenkins>' \
    --header 'Content-Type: text/xml' \
    http://{{ ip }}:8080/pluginManager/installNecessaryPlugins"
  args:
    creates: /data/jenkins/plugins/{{ item }}
  with_items: plugins
  register: plugins_result
  tags: [jenkins]

- wait_for:
    path: /data/jenkins/plugins/{{ item }}
  with_items: plugins
  tags: [jenkins]
```

I get errors like this for the plugins:
`failed: [localhost] (item=git) => {"elapsed": 300, "failed": true, "item": "git", "msg": "Timeout when waiting for file /data/jenkins/plugins/git"}`
In the Docker logs I see this:
`Apr 24, 2016 2:07:01 PM hudson.security.csrf.CrumbFilter doFilter
WARNING: No valid crumb was included in request for /pluginManager/installNecessaryPlugins. Returning 403.`
I also see similar errors in Docker logs at this task, which prevents reloading from taking place:

```
- name: Jenkins is reloaded
  uri:
    url: http://{{ ip }}:8080/reload
    method: POST
    status_code: 200,302
  when: jobs_result|changed
  ignore_errors: yes
  tags: [jenkins]
```
# Workaround

After looking here: [https://wiki.jenkins-ci.org/display/JENKINS/Remote+access+API](https://wiki.jenkins-ci.org/display/JENKINS/Remote+access+API) I created the following workaround.
## Create `ms-lifecycle/ansible/roles/jenkins/files/install_necessary_plugins.sh`:

```
#!/bin/bash


adminPass=$(tail /data/jenkins/secrets/initialAdminPassword)
crumbLine=$(curl \
--user admin:$adminPass \
"$1"':8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')

response=$(curl -X POST \
--user admin:$adminPass \
-H "$crumbLine" \
--write-out %{http_code} \
-d '<jenkins><install plugin=\"$2@latest\" /></jenkins>' \
--header 'Content-Type: text/xml' \
http://$1:8080/pluginManager/installNecessaryPlugins)



if [ "$response" -lt "400" ]
then
    exit 0
else
    exit 1
fi
```
## Create `ms-lifecycle/ansible/roles/jenkins/files/reload.sh`:

```
#!/bin/bash

adminPass=$(tail /data/jenkins/secrets/initialAdminPassword)
crumbLine=$(curl \
--user admin:$adminPass \
"$1"':8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')

response=$(curl \
-X POST \
--user admin:$adminPass \
-H "$crumbLine" \
--write-out %{http_code} \
$1:8080/reload)

if [ "$response" -lt "400" ]
then
    exit 0
else
    exit 1
fi
```
## Add to `configs` in `ms-lifecycle/ansible/roles/jenkins/defaults/main.yml`:

```
  { src: "reload.sh", dir: "/data/jenkins", file: "reload.sh", mode: "0744" },
  { src: "install_necessary_plugins.sh", dir: "/data/jenkins", file: "install_necessary_plugins.sh", mode: "0744" }
```
## Edit tasks in `ms-lifecycle/ansible/roles/jenkins/tasks/main.yml`:

```
- name: Plugins are installed
  shell: "/data/jenkins/install_necessary_plugins.sh {{ ip }} {{ item }}" #changed
  args:
    creates: /data/jenkins/plugins/{{ item }}
  with_items: plugins
  register: plugins_result
  tags: [jenkins]
```

and

```
- name: Jenkins is reloaded
  shell: "/data/jenkins/reload.sh {{ ip }}" #changed
  when: jobs_result|changed
  tags: [jenkins]
```
# 

Can you see that this is an issue (e.g. as a result of a change in the Jenkins Docker Hub image to require the CSRF token), or have I possibly misconfigured something elsewhere? If this is an issue, can you see that my workaround is adequate/robust solution?

Let me know if you need any more info!

**Comment by vfarcic** [comment]
Thank you for this PR.

The problem was introduced with the latest Jenkins release 2.0. As a temporary workaround, I fixed the version in Ansible to 1.642.4.

Your code looks good but I'm afraid that more changes will be needed. Jenkins 2.0 requires quite a few manual steps to be done during the setup (for example, to change the initial password you're using). I won't be able to work on this during the next week since I'll be in the CraftConf most of the time. 

I'd appreciate if you'd like to tackle the problem. The goal would be to remove manual steps completely. You'll see manual setup once you open Jenkins UI.

**Comment by ghost** [comment]
Thanks for the info, initially there seems to be quite a simple solution to revert the Jenkins 2.0 startup behaviour so that it mimics Jenkins 1.642.4 to an extent, by setting an environmental variable of:

```
JAVA_OPTS=-Djenkins.install.runSetupWizard=false
```

as documented here:
https://wiki.jenkins-ci.org/display/JENKINS/Features+controlled+by+system+properties
with a discussion of how it is not appropriate for production here:
https://issues.jenkins-ci.org/browse/JENKINS-34035

So a possible solution here could be changes in `roles/jenkins/tasks/main.yml` like this:

```

- name: Container is running
  docker:
    name: jenkins
    image: jenkins:latest
    env:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false #changed
    ports: 8080:8080
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /vagrant/.vagrant/machines:/machines
  register: container_result
  tags: [jenkins]
```

I imagine the insecurity isn't desirable though?

I would like to try to tackle the problem, looking at it today/yesterday I noticed a problem with my setup where jenkins slaves weren't online, I'm not sure whether that is related to the Jenkins 2.0 image or my setup so will explore some more during this week. Also want to be sure that Jenkins 2.0 doesn't have other as yet unknown consequences on this repository.
I've not contributed to a project before so please let me know if there are contribution/discussion procedures I'm not adhering to.
